### PR TITLE
Use new MET/METplus installs on Gaea

### PR DESCRIPTION
**Pull request by willmayfield**
## DESCRIPTION OF CHANGES: 
Recent versions of MET/METplus were installed on Gaea (https://dtcenter.org/community-code/metplus/metplus-4-1-existing-builds). This PR adds theirs paths to the Gaea machine file, which should enable their use in the workflow.

## TESTS CONDUCTED: 
`MET_ensemble_verification` and `MET_verification` tests need to be run on Gaea by someone with access to the platform and it needs to be confirmed that observations are staged in /lustre/f2/pdata/ncep_shared/UFS_SRW_App/develop/obs_data. Other platforms should not be impacted.

Once this is successfully tested and merged, @jessemcfarland should be able to remove the logic in https://github.com/ufs-community/ufs-srweather-app/pull/333 that avoids running the verification tests on Gaea.

### CODE REVIEW

**Comment by EdwardSnyder-NOAA** [comment]
I noticed the `obs_data` directory is missing from `/lustre/f2/pdata/ncep_shared/UFS_SRW_App/develop`. It looks like the obs_data was untarred under `ncep_shared.` I tried to mv `obs_data` to `/lustre/f2/pdata/ncep_shared/UFS_SRW_App/develop` but I got permission denied. @mark-a-potts has permissions to both these directories. Once we get `obs_data` under the correct path, I can run these tests.

**Review by JeffBeck-NOAA — APPROVED** [review]

**Review by panll — APPROVED** [review]
Looks good to me, thanks!

**Comment by gsketefian** [comment]
@EdwardSnyder-NOAA I just checked under `/lustre/f2/pdata/ncep_shared/UFS_SRW_App/develop`, and I see the `obs_data` directory there (and it is not empty).  Do you mind trying to run those two MET tests now?  Thanks.

**Comment by EdwardSnyder-NOAA** [comment]
@gsketefian - I saw the obs_data was in the right place earlier today. Unfortunately, I'm having trouble running these tests. I've been troubleshooting all day trying to figure out why I cannot run them. I'm getting an invalid account or partition when running the `launch_FV3LAM_wflow.sh` but I'm using the same account from two months ago, which worked for me.

**Pull request merged**
