### PR TITLE
Default CCPP physics option is FV3_GFS_v16

### PR DESCRIPTION
**Pull request by natalie-perlin**
updated: 
   ush/config.community.sh
   ush/config.nco.sh
   ush/config_defaults.sh

### CODE REVIEW

**Review by RatkoVasic-NOAA — APPROVED** [review]

**Review by JeffBeck-NOAA — APPROVED** [review]

**Comment by jwolff-ncar** [comment]
I don't see that the NCO config file has been updated here. That should be checked on. (Only 2 files have changed)

**Comment by JeffBeck-NOAA** [comment]
@jwolff-ncar, thanks for pointing that out.  @natalie-perlin, do you mind taking a look and opening another PR?  Thanks.

**Comment by natalie-perlin** [comment]
@JeffBeck-NOAA - current config.nco.sh has CCPP option set to FV3_GFS_v16 , too!

**Comment by JeffBeck-NOAA** [comment]
Thanks, @natalie-perlin.  I think we may be OK then.

**Pull request merged**
