### PR TITLE
Release/public v2 gaea update

### PR DESCRIPTION
**Pull request by natalie-perlin**
This update is for backward compatibility with the SRW _**release/public-v2**_ branch of the SRW App, 
https://github.com/ufs-community/ufs-srweather-app.git.

Changes are made to reflect updates in Lmod/8.7.12, miniconda3, and the hpc-stack on Gaea NOAA HPC system, installed under **epic.role** account in **/lustre/f2/dev/wpo/role.epic/contrib/** space, and maintained by EPIC.

** FILES CHANGED

The following scripts have been changed under the ./regional_workflow/ base directory:

./ush/machine/gaea.sh
./ush/load_modules_run_task.sh (contribution of @EdwardSnyder-NOAA )
./modulefiles/module-setup.sh.inc
./modulefiles/module-setup.csh.inc
./modulefiles/tasks/gaea/make_grid.local, get_extrn_ics.local, get_extrn_lbcs.local, make_orog.local, make_sfc_climo.local, make_ics.local, make_lbcs.local, run_fcst.local, run_post.local  (contribution of @EdwardSnyder-NOAA )

** TESTING PERFORMED 

The updated repository has been tested on Gaea as a part of the SRW release/public-v2 branch, 
by specifying the url for the regional_workflow in the Externals.cfg as following:

```
[regional_workflow]
protocol = git
#repo_url = https://github.com/ufs-community/regional_workflow
repo_url = https://github.com/natalie-perlin/regional_workflow
# Specify either a branch name or a hash but not both.
branch = release/public-v2-gaea-update
local_path = regional_workflow
required = True
...

```
Additional files in the SRW release/public-v2 branch were modified to sync the updated Lmod/8.7.12, miniconda3/4.12.0 and the hpc-stack initialization, under the main SRW directory, such as **./ufs-srweather-app/**:

./etc/lmod-setup.sh , lmod-setup.csh
./modulefiles/build_gaea_intel
./modulefiles/wflow_gaea

These updates of the SRW **release/public-v2** branch are being prepared as a separate PR into the 
https://github.com/ufs-community/ufs-srweather-app.git, to correspond the current changes to the regional_workflow repo, release/public-v2 branch.

The SRW has been build, and a test case grid_RRFS_CONUScompact_25km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v16 from the comprehensive test suite has been run using the rocoto and crontab table. The following stages have been successfully completed: 
make_grid 
make_orog
make_sfc_climo
get_extrn_ics
get_extrn_lbcs
make_ics
make_lbcs
run_fcst
run_post_f001 - run_post_f006.

### CODE REVIEW

**Review by EdwardSnyder-NOAA — CHANGES_REQUESTED** [review]
The get_extrn_lbcs.local file under gaea (`modulefiles/tasks/get_extrn_lbcs.local`) needs to removed. It should go under: `modulefiles/tasks/gaea/get_extrn_lbcs.local`, which you have already.

**Review by panll — APPROVED** [review]
I tested it on Hera, and it works fine.

**Review by natalie-perlin — COMMENTED** [review]
Removed a redundant module placed under ./regional_workflow/modulefiles/tasks/

**Comment by natalie-perlin** [comment]
@EdwardSnyder-NOAA  - the repo has been updated, a redundant file has been removed!

**Review by EdwardSnyder-NOAA — APPROVED** [review]

**Pull request merged**
