### PR TITLE
Bugfix:  Pass domain name to python plotting scripts

### PR DESCRIPTION
**Pull request by gsketefian**
## DESCRIPTION OF CHANGES: 
PR #[763](https://github.com/ufs-community/regional_workflow/pull/763) introduced the experiment variable `POST_OUTPUT_DOMAIN_NAME` and used it to modify the names of the UPP output files.  This PR adds `POST_OUTPUT_DOMAIN_NAME` as an argument to the python plotting scripts to enable those scripts to form the proper UPP output file names to read in.  It also modifies the batch scripts (`qsub_job.sh`, `qsub_job_diff.sh`, `sq_job.sh`, and `sq_job_diff.sh`) to add the new argument to the calls to the python plotting scripts that are called.

## TESTS CONDUCTED: 
Both python plotting scripts `plot_allvars.py` and `plot_allvars_diff.py` were run on Hera on preexisting UPP output files and completed successfully.  The batch scripts `sq_job.sh` and `sq_job_diff.sh` were also run successfully on Hera (`qsub_job.sh` and `qsub_job_diff.sh` were not run on e.g. Cheyenne).

## DEPENDENCIES:
PR # in `ufs-srweather-app`.

## DOCUMENTATION:
Modifications to the documentation are in PR #.

## ISSUE: 
Partially resolves issue #781 (still need to introduce tests in `regional_workflow` that run the plotting scripts).

## CONTRIBUTORS: 
@mark-a-potts pointed out the problem and first made the necessary fixes in the `NOAA-EPIC` fork of `regional_workflow`; @gsketefian introduced those changes to this PR and made edits to the comments and documentation.

### CODE REVIEW

**Review by mark-a-potts — APPROVED** [review]
LGTM

**Comment by dmwright526** [comment]
@gsketefian The looks good to me. The qsub_job*.sh and sq_job*.sh are also going to need to be updated with the new variable. Since we source the var_defns.sh in those job scripts, we should just need to add ${POST_OUTPUT_DOMAIN_NAME} to the last line.

**Comment by BenjaminBlake-NOAA** [comment]
@JeffBeck-NOAA  Having the domain name in the grib2 files is acceptable to NCO.  For the HRRR Alaska grib2 files, they have "ak" in them, and the NAM nest grib2 files also have domain-specific labels in the filenames.

**Review by BenjaminBlake-NOAA — APPROVED** [review]

**Comment by chan-hoo** [comment]
@JeffBeck-NOAA, as Ben mentioned above, it is a new requirement of the NCO standards (Ver. 11.0.0, Jan 19, 2022, pp. 6) "Filename format for files in com: model.tHHz.var_info.f###.**domain**.format".

**Review by chan-hoo — APPROVED** [review]

**Pull request merged**
