### PR TITLE
Add namelist option for netCDF4 when running with the 3-km NA domain; update NAM HPSS settings and WE2E tests

### PR DESCRIPTION
**Pull request by JeffBeck-NOAA**
## DESCRIPTION OF CHANGES: 
Add namelist option to use netCDF4 when running with the 3-km NA domain.  Modify HPSS settings for NAM data and update related WE2E tests.

External model data for the 2021061500 NAM WE2E test has also been staged on Hera and Jet.

## TESTS CONDUCTED: 
config.grid_RRFS_NA_3km_ics_FV3GFS_lbcs_FV3GFS_suite_RRFS_v1alpha.sh
config.grid_RRFS_CONUS_25km_ics_NAM_lbcs_NAM_suite_HRRR.sh - updated to use 2021061500; HPSS retrieval now works.
config.grid_RRFS_CONUS_25km_ics_NAM_lbcs_NAM_suite_RRFS_v1beta.sh - updated to use 2021061500; HPSS retrieval now works.

## ISSUE (optional): 
Fixes the 3-km NA WE2E test and prepares updates to the NAM WE2E tests mentioned in Issue #673. 

## CONTRIBUTORS (optional): 
Thanks to @JacobCarley-NOAA for the netCDF fix when running with the 3-km NA domain.

### CODE REVIEW

**Comment by chan-hoo** [comment]
@JeffBeck-NOAA, I confirmed that the NA we2e test worked well on Hera. However, the NAM data files for the other two we2e tests are not available on Hera: "The directory extrn_mdl_source_dir containing the user-staged external model files does not exist". Can you copy them to Hera?

**Comment by JeffBeck-NOAA** [comment]
> @JeffBeck-NOAA, I confirmed that the NA we2e test worked well on Hera. However, the NAM data files for the other two we2e tests are not available on Hera: "The directory extrn_mdl_source_dir containing the user-staged external model files does not exist". Can you copy them to Hera?

@chan-hoo, thanks for testing.  I've copied the NAM files to the WE2E external model data location on Hera.  Can you try testing again?  Thanks.

**Comment by JeffBeck-NOAA** [comment]
> @JeffBeck-NOAA, I got the same error: extrn_mdl_source_dir = "/scratch2/BMC/det/Gerard.Ketefian/UFS_CAM/staged_extrn_mdl_files/NAM/2021061500". Where did you copy the files? I think you didn't merge #701 into your branch.

Thanks @chan-hoo.  I just merged in the latest develop branch, which updates the pointer for the external model data location for the WE2E tests.  It should work now.  Thanks!

**Comment by chan-hoo** [comment]
@JeffBeck-NOAA, it worked!

**Review by chan-hoo — APPROVED** [review]

**Review by jwolff-ncar — APPROVED** [review]

**Pull request merged**
