### PR TITLE
Increase size of RRFS CONUS grid

### PR DESCRIPTION
**Pull request by BenjaminBlake-NOAA**
## DESCRIPTION OF CHANGES: 
The size of the 3-km CONUS grid is increased in order to produce output on the operational HRRR / NAM nest grid without undefined points.  This grid will be used by the RRFS real-time parallels, so the name should be kept as RRFS_CONUS_3km.  The current RRFS_CONUS_3km grid will be kept in the workflow for any users who wish to continue using it, but it has been renamed to RRFS_CONUS**compact**_3km.  This smaller version of the CONUS grid can be initialized off of HRRR data.

The 13-km and 25-km RRFS CONUS grids have also been updated to reflect the changes to the 3-km RRFS CONUS grid.  Thanks @JeffBeck-NOAA for doing this.  The current 13-km and 25-km grids have also been preserved for any users who wish to continue using them.  New WE2E tests were added for the new CONUS grids.

- List of the renamed WE2E tests (RRFS_CONUS -> RRFS_CONUScompact):
grid_RRFS_CONUScompact_13km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v16
grid_RRFS_CONUScompact_13km_ics_HRRR_lbcs_RAP_suite_HRRR
grid_RRFS_CONUScompact_13km_ics_HRRR_lbcs_RAP_suite_RRFS_v1alpha
grid_RRFS_CONUScompact_13km_ics_HRRR_lbcs_RAP_suite_RRFS_v1beta
grid_RRFS_CONUScompact_25km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v16
grid_RRFS_CONUScompact_25km_ics_HRRR_lbcs_HRRR_suite_HRRR
grid_RRFS_CONUScompact_25km_ics_HRRR_lbcs_HRRR_suite_RRFS_v1beta
grid_RRFS_CONUScompact_25km_ics_HRRR_lbcs_RAP_suite_HRRR
grid_RRFS_CONUScompact_25km_ics_HRRR_lbcs_RAP_suite_RRFS_v1alpha
grid_RRFS_CONUScompact_25km_ics_HRRR_lbcs_RAP_suite_RRFS_v1beta
grid_RRFS_CONUScompact_3km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v16
grid_RRFS_CONUScompact_3km_ics_HRRR_lbcs_RAP_suite_GFS_v15p2
grid_RRFS_CONUScompact_3km_ics_HRRR_lbcs_RAP_suite_HRRR
grid_RRFS_CONUScompact_3km_ics_HRRR_lbcs_RAP_suite_RRFS_v1alpha
grid_RRFS_CONUScompact_3km_ics_HRRR_lbcs_RAP_suite_RRFS_v1beta
nco_grid_RRFS_CONUScompact_25km_ics_HRRR_lbcs_RAP_suite_HRRR

## TESTS CONDUCTED: 
- WE2E tests:
nco_grid_RRFS_CONUS_13km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v16 (O)
nco_grid_RRFS_CONUS_3km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v15_thompson_mynn_lam3km (O)
nco_grid_RRFS_CONUScompact_25km_ics_HRRR_lbcs_RAP_suite_HRRR (O)
grid_CONUS_25km_GFDLgrid_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v16 (O)
grid_CONUS_3km_GFDLgrid_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v16 (O)
grid_RRFS_AK_13km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v16 (O)
grid_RRFS_AK_3km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v16 (O)
grid_RRFS_CONUS_13km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v15p2 (O)
grid_RRFS_CONUS_13km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v16 (O)
grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_2017_gfdlmp_regional (O)
grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_2017_gfdlmp (O)
grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v15p2 (O)
grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v16 (O)
grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_RAP_suite_HRRR (O)
grid_RRFS_CONUS_25km_ics_GSMGFS_lbcs_GSMGFS_suite_GFS_2017_gfdlmp (O)
grid_RRFS_CONUS_25km_ics_GSMGFS_lbcs_GSMGFS_suite_GFS_v15p2 (O)
grid_RRFS_CONUS_25km_ics_NAM_lbcs_NAM_suite_HRRR (O)
grid_RRFS_CONUS_25km_ics_NAM_lbcs_NAM_suite_RRFS_v1beta (O)
grid_RRFS_CONUS_3km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v15p2 (O)
grid_RRFS_CONUS_3km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v15_thompson_mynn_lam3km (O)
grid_RRFS_CONUS_3km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v16 (O)
grid_RRFS_CONUScompact_13km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v16 (O)
grid_RRFS_CONUScompact_13km_ics_HRRR_lbcs_RAP_suite_HRRR (O)
grid_RRFS_CONUScompact_13km_ics_HRRR_lbcs_RAP_suite_RRFS_v1alpha (O)
grid_RRFS_CONUScompact_13km_ics_HRRR_lbcs_RAP_suite_RRFS_v1beta (O)
grid_RRFS_CONUScompact_25km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v16 (O)
grid_RRFS_CONUScompact_25km_ics_HRRR_lbcs_HRRR_suite_HRRR (O)
grid_RRFS_CONUScompact_25km_ics_HRRR_lbcs_HRRR_suite_RRFS_v1beta (O)
grid_RRFS_CONUScompact_25km_ics_HRRR_lbcs_RAP_suite_HRRR (O)
grid_RRFS_CONUScompact_25km_ics_HRRR_lbcs_RAP_suite_RRFS_v1alpha (O)
grid_RRFS_CONUScompact_25km_ics_HRRR_lbcs_RAP_suite_RRFS_v1beta (O)
grid_RRFS_CONUScompact_3km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v16 (O)
grid_RRFS_CONUScompact_3km_ics_HRRR_lbcs_RAP_suite_GFS_v15p2 (O)
grid_RRFS_CONUScompact_3km_ics_HRRR_lbcs_RAP_suite_HRRR (O)
grid_RRFS_CONUScompact_3km_ics_HRRR_lbcs_RAP_suite_RRFS_v1alpha (O)
grid_RRFS_CONUScompact_3km_ics_HRRR_lbcs_RAP_suite_RRFS_v1beta (O)
grid_RRFS_NA_3km_ics_FV3GFS_lbcs_FV3GFS_suite_RRFS_v1alpha (O)
grid_RRFS_SUBCONUS_3km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v16 (O)
grid_RRFS_SUBCONUS_3km_ics_HRRR_lbcs_RAP_suite_GFS_v15p2 (O)
community_ensemble_008mems (O)
community_ensemble_2mems (O)
deactivate_tasks (O)
get_from_HPSS_ics_FV3GFS_lbcs_FV3GFS_fmt_grib2_2019061200 (O)
get_from_HPSS_ics_FV3GFS_lbcs_FV3GFS_fmt_grib2_2019101818 (O)
get_from_HPSS_ics_FV3GFS_lbcs_FV3GFS_fmt_grib2_2020022518 (O)
get_from_HPSS_ics_FV3GFS_lbcs_FV3GFS_fmt_grib2_2020022600 (O)
get_from_HPSS_ics_FV3GFS_lbcs_FV3GFS_fmt_grib2_2021010100 (O)
get_from_HPSS_ics_FV3GFS_lbcs_FV3GFS_fmt_nemsio_2019061200 (O)
get_from_HPSS_ics_FV3GFS_lbcs_FV3GFS_fmt_nemsio_2019101818 (O)
get_from_HPSS_ics_FV3GFS_lbcs_FV3GFS_fmt_nemsio_2020022518 (O)
get_from_HPSS_ics_FV3GFS_lbcs_FV3GFS_fmt_nemsio_2020022600 (O)
get_from_HPSS_ics_FV3GFS_lbcs_FV3GFS_fmt_nemsio_2021010100 (O)
get_from_HPSS_ics_FV3GFS_lbcs_FV3GFS_fmt_nemsio (O)
get_from_HPSS_ics_FV3GFS_lbcs_FV3GFS_fmt_netcdf_2021062000 (O)
get_from_HPSS_ics_GSMGFS_lbcs_GSMGFS (O)
get_from_HPSS_ics_HRRR_lbcs_RAP (O)
get_from_HPSS_ics_RAP_lbcs_RAP (O)
inline_post (O)
MET_ensemble_verification (O)
MET_verification (O)
nco_ensemble (O)
new_ESGgrid (O)
new_GFDLgrid__GFDLgrid_USE_GFDLgrid_RES_IN_FILENAMES_eq_FALSE (O)
new_GFDLgrid__GFDLgrid_USE_GFDLgrid_RES_IN_FILENAMES_eq_TRUE (O)
new_GFDLgrid (O)
pregen_grid_orog_sfc_climo (O)
specify_DOT_OR_USCORE (O)
specify_DT_ATMOS_LAYOUT_XY_BLOCKSIZE (O)
specify_RESTART_INTERVAL (O)

## ISSUE: 
Fixes issue mentioned in #723 

## CONTRIBUTORS: 
@JeffBeck-NOAA @chan-hoo

### CODE REVIEW

**Comment by gsketefian** [comment]
@BenjaminBlake-NOAA Since the `RRFS_CONUS_[25|13|3]km` grids are currently used in many WE2E tests but are being redefined in this PR, I think it would be a good idea to rerun all such tests.  

Since PR #708 by @ywangwof that is required for the release requires an update to the weather model hash, maybe it would make sense to combine the two PRs in a temporary branch so they can be tested together.  If we go that route, probably a full set of tests would be the way to go.  We can split the work among several people.  @mkavulich Any thoughts since you've been running the full set of tests as well? @EdwardSnyder-NOAA @mark-a-potts @christopherwharrop-noaa @JeffBeck-NOAA

**Comment by chan-hoo** [comment]
@gsketefian, I've submitted the following WE2E test along with the above tests on Orion: grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_2017_gfdlmp_regional
grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v15p2
grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_RAP_suite_HRRR
grid_RRFS_CONUS_25km_ics_HRRR_lbcs_HRRR_suite_RRFS_v1beta
grid_RRFS_CONUS_25km_ics_HRRR_lbcs_RAP_suite_RRFS_v1alpha
grid_RRFS_CONUS_3km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v15_thompson_mynn_lam3km
grid_RRFS_CONUS_13km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v15p2
grid_RRFS_NA_3km_ics_FV3GFS_lbcs_FV3GFS_suite_RRFS_v1alpha
community_ensemble_2mems
nco_grid_RRFS_CONUS_25km_ics_HRRR_lbcs_RAP_suite_HRRR
nco_grid_RRFS_CONUS_13km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v16
nco_grid_RRFS_CONUS_3km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v15_thompson_mynn_lam3km
nco_ensemble

**Comment by chan-hoo** [comment]
I found out we should update the pre-generated fix files (grid, orog, sfc_climo) of the RRFS-CONUS domains for the 'nco' mode.

**Comment by gsketefian** [comment]
@chan-hoo If most of the tests you ran were successful, I think we can copy the grid, orog, and sfc_climo files for the new grids to the App's data directories (e.g. on Hera, it's `/scratch2/BMC/det/UFS_SRW_App/UFS_CAM/NCO_dirs/fix_lam`).  The old grid directories there will have to be renamed and new ones created for the new grids.  And all that will have to be done on all platforms.  I would do it in coordination with @mkavulich.

**Comment by chan-hoo** [comment]
@gsketefian @JeffBeck-NOAA  @BenjaminBlake-NOAA, two tests, "grid_RRFS_CONUS_25km_ics_HRRR_lbcs_HRRR _suite_RRFS_v1beta", "grid_RRFS_CONUS_25km_ics_HRRR_lbcs_RAP_suite_RRFS_v1alpha" failed at 'make_ics/make_lbcs' and 'make_ics', respectively. I suspect that there is something wrong in HRRR.

**Comment by BenjaminBlake-NOAA** [comment]
@chan-hoo  Are those two tests using HRRR data for ICs/LBCs?  If so then those tests will likely not work because the new versions of the RRFS CONUS grids are slightly larger than the HRRR CONUS output domain.

**Comment by BenjaminBlake-NOAA** [comment]
@chan-hoo  Yes I think so.  For any WE2E tests that currently use the HRRR, the new RRFS CONUS grids should not be used, and the old grids with the HRRRIC extension should be used instead.

**Comment by chan-hoo** [comment]
@gsketefian, I've added the fix files of the new RRFS_CONUS domains for the nco we2e tests to WCOSS_dell_p3 and Orion. The nco we2e tests except for 'nco_grid_RRFS_CONUS_25km_ics_HRRR_lbcs_RAP_suite_HRRR' were complete on the WCOSS dell and Orion successfully.

**Comment by gsketefian** [comment]
@BenjaminBlake-NOAA @chan-hoo Some comments and questions:

1) After talking with @JeffBeck-NOAA about this, we thought the "HRRIC" addition to the original grids' names is somewhat misleading because people may think they can only be initialized with HRRR.  We think something like "RRFS_CONUScompact_XXkm" is more descriptive.  Can we make this change?

2) Since the RRFS_CONUScompact_3km is still of interest (at least to DTC) and the RRFS_CONUScompact_13km is of interest to CMAQ (I think according to @BenjaminBlake-NOAA), we should have WE2E tests for these that use HRRR ICs and RAP LBCs.

3) Do the tests for the new domains now all use FV3GFS for ICs and LBCs?  Or do you also use RAP?  It would be nice to see in the PR message a list of all the tests that are now using the new grids as well as a list of "new" tests that are using the original grids.

4) We will have to update the pre-generated (grid, orog, and sfc_climo) files on all supported level-1 platforms.  @chan-hoo Can you list the paths of those files on Orion?  @EdwardSnyder-NOAA @mark-a-potts can you guys help transfer those files over to the other platforms (if you have access to Orion)?  I can't work on that for a while since I have 2 significant PRs to review/finish soon.   

Thanks.

**Comment by BenjaminBlake-NOAA** [comment]
@gsketefian  Your proposed name change with 1) is fine by me.  I think Jacob or Curtis suggested using HRRRIC, but I agree that it could potentially be misleading.  I can go ahead and update my feature/rrfsconus branch with those name changes today.  I will defer to @chan-hoo for items 2-4

**Comment by chan-hoo** [comment]
@EdwardSnyder-NOAA , @mark-a-potts , You can find the new data on Orion: "/work/noaa/fv3-cam/UFS_SRW_App/FV3LAM_pregen/" and "/work/noaa/fv3-cam/UFS_SRW_App/FIXLAM_NCO_BASE".  (1) new domain: RRFS_CONUS_[25,13,3]km , (2) Old domains: RRFS_CONUScompact_[25,13,3]km

**Comment by gsketefian** [comment]
@JacobCarley-NOAA @CurtisAlexander-NOAA I suggested changing the old (original) grid names from "RRFS_CONUS_XXkm_HRRRIC" to "RRFS_CONUScompact_XXkm" since (1) "HRRRIC" might mislead people into thinking these grids can only be initialized with HRRR, and (2) "compact" gives a better idea of how these grids relate to the new, more extensive ones.  What do you think?

**Comment by EdwardSnyder-NOAA** [comment]
@chan-hoo - I'm getting a permission denied when trying to access these directories: ("/work/noaa/fv3-cam/UFS_SRW_App/FV3LAM_pregen/" and "/work/noaa/fv3-cam/UFS_SRW_App/FIXLAM_NCO_BASE") on Orion. But yeah, I can help out. Perhaps the new data is staged elsewhere?

**Comment by chan-hoo** [comment]
@EdwardSnyder-NOAA , can you try it again? I've changed their permissions. 
drwxrwsrw-  8 chjeon fv3-cam  4096 Apr  5 12:36 FIXLAM_NCO_BASE
drwxrwsrwx 14 chjeon fv3-cam  4096 Apr  5 12:37 FV3LAM_pregen

**Comment by EdwardSnyder-NOAA** [comment]
@chan-hoo - Sorry I didn't realize this before, but I also don't have access to the "UFS_SRW_App" directory. Getting a permission denied there too.

**Comment by chan-hoo** [comment]
@EdwardSnyder-NOAA, it is strange. 
drwxrwSrw-  7 chjeon   fv3-cam   4096 Mar 31 07:50 UFS_SRW_App
I'll copy the data to Hera once it is back tomorrow and let you know where you can find it.

**Comment by mkavulich** [comment]
@chan-hoo As Gerard mentioned, I am in the middle of unifying the staged data across platforms, so I can take care of copying the new pregenerated files to from Orion to Hera, Jet, and Cheyenne when the maintenance period is finished today.

Also, this is not directly related to this PR, but is there a reason to keep the pre-generated data for NCO and community cases separate? Are the output files from make_grid, make_orog, and make_sfc_climo not the same for NCO and community cases using the same grid?

In my proposal to simplify and standardize the staged data (https://github.com/ufs-community/ufs-srweather-app/issues/231) I proposed merging the directories for pregenerated data, but anyone thinks they should be kept separate going forward please let me know.

**Comment by JacobCarley-NOAA** [comment]
@gsketefian @chan-hoo 'compact' is good with me as well.

**Comment by chan-hoo** [comment]
@mkavulich, I agree with you. I don't see any reasons to keep both of them separately.

**Comment by chan-hoo** [comment]
@mkavulich, Oh.. I got it. Thank you! I've changed the permission.
drwxrwsrwx  7 chjeon   fv3-cam   4096 Mar 31 07:50 UFS_SRW_App
Can you try it again?

**Comment by chan-hoo** [comment]
@gsketefian, all the we2e tests were complete successfully.

**Comment by mkavulich** [comment]
@chan-hoo Looks good! Transferring the files to other machines now, I can let you know when that is complete.

**Comment by chan-hoo** [comment]
@gsketefian @JeffBeck-NOAA, I found one we2e test failed ('grid_RRFS_CONUS_25km_ics_GSMGFS_lbcs_GSMGFS_suite_GFS_v16'). The error says: "FATAL from PE     4: compute_qs: saturation vapor pressure table overflow, nbad=      1". Do you have any idea of this?

**Comment by mkavulich** [comment]
@chan-hoo I can confirm you can ignore that failure. Thanks for bringing it up because I forgot to open a new issue for that one, it's open now at #731

**Comment by BenjaminBlake-NOAA** [comment]
@JeffBeck-NOAA  I believe @chan-hoo has some output on WCOSS from his WE2E tests that I could take a look at for the new 13-km and 25-km grids.  @chan-hoo  can you point me to that when you get a chance?  Thanks

**Comment by chan-hoo** [comment]
@BenjaminBlake-NOAA @JeffBeck-NOAA, you can find the results on the dell: /gpfs/dell2/emc/modeling/noscrub/Chan-Hoo.Jeon/test_srw/expt_dirs/

**Review by mkavulich — APPROVED** [review]

**Comment by gsketefian** [comment]
@JeffBeck-NOAA The latest plots (whole grids + grid corners) are here on Hera:
```
/scratch2/BMC/det/Gerard.Ketefian/UFS_CAM/TEST_Ligia_namelists/ufs-srweather-app/regional_workflow/ush/NCL/*Jeff_CONUS*.png
```
The 25km and 13km native grids look good to me, i.e. they look like they're the best you can do to match the 3km native grid. 
 The write-component grids are not symmetric with respect to the native grids though, and they're also not symmetric with respect to the HRRR grid (the 3km write-component grid tries to match the HRRR grid as closely as possible).  We can further refine the 25km and 13km grids if you like to get them as close as possible to the HRRR grid.

**Review by JeffBeck-NOAA — APPROVED** [review]

**Pull request merged**
