### PR TITLE
[develop] Add MET/METplus to Jet

### PR DESCRIPTION
**Pull request by EdwardSnyder-NOAA**
## DESCRIPTION OF CHANGES: 
Added MetPlus file paths to the Jet machine file in the develop branch. A similar PR #797 was approved for the release branch.

## TESTS CONDUCTED: 
Ran `MET_verification` and `MET_ensemble_verification` successfully on Jet.

## DEPENDENCIES:
None.

## DOCUMENTATION:
No documentation changes are needed.

### CODE REVIEW

**Review by JeffBeck-NOAA — APPROVED** [review]

**Comment by willmayfield** [comment]
Did you check the MET outputs and logs? I had hoped to put this change in #779 but ran into errors from MET, even though the workflow tasks succeeded. I was thinking it needs an appropriate run_vx.local modulefile and/or updates to the miniconda environment.

**Comment by EdwardSnyder-NOAA** [comment]
> Did you check the MET outputs and logs? I had hoped to put this change in #779 but ran into errors from MET, even though the workflow tasks succeeded. I was thinking it needs an appropriate run_vx.local modulefile and/or updates to the miniconda environment.

Hi @willmayfield - I didn't check the logs or outputs. What sort of errors did you receive? I'm noticing the `ModuleNotFoundError: No module named 'dateutil'` error is in most of the vx logs.

**Comment by willmayfield** [comment]
> Hi @willmayfield - I didn't check the logs or outputs. What sort of errors did you receive? I'm noticing the `ModuleNotFoundError: No module named 'dateutil'` error is in most of the vx logs.

Yep, that's what I see too.

**Review by natalie-perlin — APPROVED** [review]

**Comment by EdwardSnyder-NOAA** [comment]
Added `modulefiles/tasks/jet/run_vx.local` script, which removed `ModuleNotFoundError: No module named 'dateutil'` errors and resulted in a successful run of both the `MET_verification` and `MET_ensemble_verification` tests.

**Review by willmayfield — APPROVED** [review]
Compared a few MET stat files to the same test on Hera. There were very small numerical differences, likely within reason between platforms.

**Comment by EdwardSnyder-NOAA** [comment]
Thanks @willmayfield for doing the comparison!

**Pull request merged**
