### PR TITLE
Adding new E2E non-compact grids

### PR DESCRIPTION
**Pull request by EdwardSnyder-NOAA**
## DESCRIPTION OF CHANGES: 
Added 6 new non-compact grids for testing. See the list below. These tests will be included in the upcoming SRW v2 Release. These changes will be merged into the develop branch as well.

- config.grid_RRFS_CONUS_13km_ics_FV3GFS_lbcs_FV3GFS_suite_HRRR.sh
- config.grid_RRFS_CONUS_13km_ics_FV3GFS_lbcs_FV3GFS_suite_RRFS_v1beta.sh
- config.grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_FV3GFS_suite_HRRR.sh
- config.grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_FV3GFS_suite_RRFS_v1beta.sh
- config.grid_RRFS_CONUS_3km_ics_FV3GFS_lbcs_FV3GFS_suite_HRRR.sh
- config.grid_RRFS_CONUS_3km_ics_FV3GFS_lbcs_FV3GFS_suite_RRFS_v1beta.sh

## TESTS CONDUCTED: 
The first four tests listed above ran on Orion successfully. The last two, RRFS_CONUS_3km, grids ran successfully on Parallel Works AWS cluster.

## DEPENDENCIES:
No Dependencies.

## DOCUMENTATION:
No documentation changes are needed. 

## CONTRIBUTORS (optional):

### CODE REVIEW

**Comment by JeffBeck-NOAA** [comment]
Agree with this.  Thanks, @gsketefian, @EdwardSnyder-NOAA!

**Review by JeffBeck-NOAA — APPROVED** [review]

**Comment by gsketefian** [comment]
@EdwardSnyder-NOAA I'm just waiting to hear back from EMC (@BenjaminBlake-NOAA or @RatkoVasic-NOAA) and if they're ok with it, we can approve and merge.

**Review by RatkoVasic-NOAA — APPROVED** [review]

**Comment by gsketefian** [comment]
@EdwardSnyder-NOAA Go ahead and merge after you can confirm that the 3km tests passed.  Thanks for creating this PR.

**Comment by gsketefian** [comment]
@EdwardSnyder-NOAA And please fix up the documentation section of the PR message.  Currently says "Documentation might need to be" and that's all.

**Review by BenjaminBlake-NOAA — APPROVED** [review]
Yes, I agree about adding these tests to the release since we are officially supporting those grids.  Thanks

**Comment by EdwardSnyder-NOAA** [comment]
@gsketefian 3- I've updated the documentation section. 

The 3km tests ran successfully on the Parallel Works AWS cluster.

**Pull request merged**
