### PR TITLE
Pin down hera miniconda3 module file version.

### PR DESCRIPTION
**Pull request by christinaholtNOAA**
## DESCRIPTION OF CHANGES: 
Pin down the version of miniconda3 on Hera, and do not append to the module path. Addresses Issue https://github.com/ufs-community/ufs-srweather-app/issues/256.

## TESTS CONDUCTED: 
Command line tests for loading modules.

## DEPENDENCIES:
Should be tested and merged with SRW [PR #257](https://github.com/ufs-community/ufs-srweather-app/pull/257)

## ISSUE : 
Addresses the SRW Issue [#256](https://github.com/ufs-community/ufs-srweather-app/issues/256)

## CONTRIBUTORS (optional): 
@danielabdi-noaa @JeffBeck-NOAA

### CODE REVIEW

**Review by danielabdi-noaa — APPROVED** [review]

**Review by JeffBeck-NOAA — APPROVED** [review]

**Comment by christinaholtNOAA** [comment]
I'd like to auto-test this on hera, but need a couple admin items to work out first. I hope to get that taken care of by the end of today.

**Comment by christinaholtNOAA** [comment]
I have accidentally pushed the working branch to the authoritative repository in SRW instead of my own fork due to a copy paste error on my end. It led to the failure of the autotest suite since it couldn't test with the corresponding SRW branch that also contains fixes. I have addressed that issue, and am restarting the tests now.

**Comment by venitahagerty** [comment]
Machine: hera
Compiler: intel
Job: WE
Repo location: /scratch1/BMC/zrtrr/rrfs_ci/autoci/pr/936360409/20220518202014/ufs-srweather-app
Build was Successful
Generating Workflow Failed
ERROR:
  From function:  "generate_FV3LAM_wflow"
  In file:  "generate_FV3LAM_wflow.sh"
  Full path to file:  "/scratch1/BMC/zrtrr/rrfs_ci/autoci/pr/936360409/20220518202014/ufs-srweather-app/regional_workflow/ush/generate_FV3LAM_wflow.sh"
  Errors found: check your python environment

  Instructions for setting up python environments can be found on the web:
  https://github.com/ufs-community/ufs-srweather-app/wiki/Getting-Started


Exiting with nonzero status.
If test failed, please make changes and add the following label back:
ci-hera-intel-WE

**Comment by venitahagerty** [comment]
Machine: hera
Compiler: intel
Job: WE
Repo location: /scratch1/BMC/zrtrr/rrfs_ci/autoci/pr/936360409/20220518210516/ufs-srweather-app
Build was Successful
Generating Workflow Failed
ERROR:
  From function:  "generate_FV3LAM_wflow"
  In file:  "generate_FV3LAM_wflow.sh"
  Full path to file:  "/scratch1/BMC/zrtrr/rrfs_ci/autoci/pr/936360409/20220518210516/ufs-srweather-app/regional_workflow/ush/generate_FV3LAM_wflow.sh"
  Errors found: check your python environment

  Instructions for setting up python environments can be found on the web:
  https://github.com/ufs-community/ufs-srweather-app/wiki/Getting-Started


Exiting with nonzero status.
If test failed, please make changes and add the following label back:
ci-hera-intel-WE

**Comment by venitahagerty** [comment]
Machine: hera
Compiler: intel
Job: WE
Repo location: /scratch1/BMC/zrtrr/rrfs_ci/autoci/pr/936360409/20220519172015/ufs-srweather-app
Build was Successful
Rocoto jobs started
Long term tracking will be done on 10 experiments
If test failed, please make changes and add the following label back:
ci-hera-intel-WE

**Pull request merged**
